
spring:
  datasource:
    url: jdbc:h2:mem:loyalty_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings.web-allow-others: false
      settings.trace: false
      path: /h2-console